### ISSUE TITLE
我想请问光源阴影何时会加入？

### ISSUE THREAD

**Issue by smspk** [ray-cast/ray-mmd#10]
有关光源阴影，这很难实现么？现在的效果已经很十分漂亮了，就是光源不会产生阴影有些遗憾。: /

最后十分感谢你所做的！真的很漂亮。

**Comment by ray-cast** [comment]
光影阴影现在聚光灯和点光源已经有了，比如吧点光源丢到MMD中后然后LightMap中选择point_lighting_s0.fx

**Comment by smspk** [comment]
感谢回复，有了影子整个世界都完整了 _(:3ゝ∠)_

还有一个问题，昏暗的场景，暗处失真非常严重，这是哪方面的原因？应该不是显示器的问题，看电影和

使用photoshop修图都不会有这么严重的失真。渲染器的原因的话，可以做哪些修改提高色深么？

**Comment by ray-cast** [comment]
不太明白说的什么，有效果图么，或者加这个群吧122103096
