### ISSUE TITLE
ray.x file error

### ISSUE THREAD

**Issue by SyerC** [ray-cast/ray-mmd#103]
I've used raycast before and have only recently come across this error, i don't know how to fix it. I've never had this problem before. I'm not tech savvy enough to know what this error could mean, i'd appreciate any help so that i can get back to using Raycast like normal!

I am on the latest versions of both MMD and MME

![Untitled](https://user-images.githubusercontent.com/49575191/66708844-05fa4d80-ed4f-11e9-83c2-7c5583aea9c7.png)

**Comment by Fau13F** [comment]
Hello ! I had this problem before and I know how to fix it !
This is just the files name ! It is asked to be "DefaultLED" but if you go see in your folder it's written "Default LED" (with space). You just have to rename your file and open again MMD + load ray-cast. The same goes with ssao. It asks to be "SSAOvisibility1.0" but your file is named "SSAO visibility 1.0"

**Comment by SyerC** [comment]
> Hello ! I had this problem before and I know how to fix it !
> This is just the files name ! It is asked to be "DefaultLED" but if you go see in your folder it's written "Default LED" (with space). You just have to rename your file and open again MMD + load ray-cast. The same goes with ssao. It asks to be "SSAOvisibility1.0" but your file is named "SSAO visibility 1.0"

Hello, finally had a chance to test this out and you were right, thank you for your help !!
