### ISSUE TITLE
Weird mouth glow using a point light

### ISSUE THREAD

**Issue by HandMeTheMaik** [ray-cast/ray-mmd#105]
Hello! I've used raycast for about two years, but I'm only now really diving into complex features the effect provides. I recently discovered the lighting folder, which I've garnered some decent results with, but one thing has bothered me. 
Whenever I use TubeLight or RectangleLight, Miku decides to shoot a light beam from her mouth, just to spite me. 
![image](https://user-images.githubusercontent.com/55266548/71471922-a4b31980-2796-11ea-9748-f0cb138fa5ec.png)
I don't know why this is happening. It's pretty annoying. Any help would be appreciated :))

**Comment by Fau13F** [comment]
it's normal it's because you assigned a smooth material on the tongue i think. maybe the tongue subset come with the eyes or something where you add a clearcoat or anisotropy, just simply change it ^^

**Comment by HandMeTheMaik** [comment]
I actually found the fix for this a couple days ago! I was using the regular spotlight_lighting rather than spotlight_shadow. Thank you for the tip tho!
