### ISSUE TITLE
What are some good materials for stages?

### ISSUE THREAD

**Issue by HandMeTheMaik** [ray-cast/ray-mmd#106]
Hey there, I've just got a simple question for any experienced RayCast users. 

Do y'all know of any good stage materials? All the ones I can find are dedicated to skin, eyes, etc., basically just stuff for the character, not the stage. I'm looking for materials that'll give the floor of my stage some shine, like the WorkingFloor effect. Maybe some nice metal materials, too! Any help is appreciated!

**Comment by LadyLuci** [comment]
I think you have to make your own normal maps, there are a bunch of tutorials on youtube on how to make them. The normal maps in the raycast folder are just presets.
