### ISSUE TITLE
"Post Effect cannot be specified" when loading ray.fx

### ISSUE THREAD

**Issue by LoganDark** [ray-cast/ray-mmd#108]
![image](https://user-images.githubusercontent.com/4723091/75030108-47ff7280-5458-11ea-9c99-3b8f2bcaf1b5.png)

Happens if I put the effect on (default), or the 'ray controller'

mmd 9.32, mmeffect 0.37

MMD does have antialiasing but I turned it off here

![image](https://user-images.githubusercontent.com/4723091/75030269-9ad92a00-5458-11ea-8fb9-b65e2964d0bc.png)

**Comment by LoganDark** [comment]
Oops. Works if I drag ray.x into the window.

**Comment by chillcf** [comment]
> Oops. Works if I drag ray.x into the window.

THANK YOU I LOVE YOU KISS KISSS 😍😍😍😘🥰😘😘😘🤩🤗😍😘🤗😘😚😙
