### ISSUE TITLE
使用法线贴图时 路径 \被忽略

### ISSUE THREAD

**Issue by 872517414** [ray-cast/ray-mmd#11]
![1](https://cloud.githubusercontent.com/assets/9050713/20237919/652b6aea-a91a-11e6-961a-f52d965fc880.png)

**Comment by 872517414** [comment]
搞错，搞到main里了

**Comment by 872517414** [comment]
发现还是一样被忽略

**Comment by 872517414** [comment]
原来是用正斜杠= =然而这是Win不是Linux类

**Comment by ray-cast** [comment]
linux也是／啊，用＼的话要用"＼＼"

**Comment by 872517414** [comment]
原来是要用正斜杠，少打个要
