### ISSUE TITLE
How do I use ray's built-in Bokeh effect?

### ISSUE THREAD

**Issue by HandMeTheMaik** [ray-cast/ray-mmd#112]
I'm tired. Please be patient with me.
So, I have bokeh_quality enabled, and I'm messing with the MeasureMode and Focal facials and whatnot, but I'm not seeing any DOF. Would I only see it after I rendered the video? Can someone please help me out?

**Comment by nasa459** [comment]
+1
I have the same problem.

**Comment by HandMeTheMaik** [comment]
Hey, I actually figured it out. 
If you enable Bokeh in the middle of a project, then DOF won't work. 
If you start a new project with Bokeh enabled, it'll work. You just have to adjust the DOF facials to achieve your desired effect. 
Hopefully this explanation helps a bit!
