### ISSUE TITLE
Problem with loading files..

### ISSUE THREAD

**Issue by cactixrythmix** [ray-cast/ray-mmd#120]
Hello! I'm fairly new to MMD and i've been having this one issue with RayCast.
whenever i load pmx files, i have to manually load their fx files myself, example: when i load the Grand Canyon file, i have to load the skybox_hdr.fx along with it myself. This way, i can't load ray.x. I've been looking up MME and Raycast tutorials and everyone's files all seem to load correctly. How do i fix this?
edit: i found the appropriate word i should use. My files don't "autoload". I've tried putting my effects in the Userfile/Accessory/Effects folder i made, its no use.

**Comment by tERB00** [comment]
What is the full path to your skybox folder? Does it have special characters?
You have to load ray.x first before loading skyboxes and other ray-mmd stuff.
And read error messages carefully. It always says what's wrong and which files it can't allocate.

**Comment by cactixrythmix** [comment]
OKAY SO I KNOW IT'S BEEN MONTHS BUT I FINALLY FIGURED IT OUT!
Since i have a French computer, the path i chose for my MMD file wasn't readable, the path being on my ACTUAL desktop. I moved it to the "desktop" folder i found that was pinned on the side on my documents app and, low and behold, it worked out! I'll leave this here for ppl who have foreign computers <3
