### ISSUE TITLE
Weird shadow problem.

### ISSUE THREAD

**Issue by Neoly805** [ray-cast/ray-mmd#123]
Hi. I'm not the new MMD'er. I've been working with ray mmd for 2 years. I learned a lot of new things, including making my own skybox, and I have no problems with that. I created a skybox and noticed a very dark shadow. I did some skyboxes to see if the same problem occurs, but it doesn't. Here you have photos of both skyboxes .

![Untitled255_20210212150207](https://user-images.githubusercontent.com/70794714/107777883-b2818080-6d43-11eb-9f2a-1a7d2765aa65.png)

Can someone please explain to me why this is so?

**Comment by tERB00** [comment]
It would help if you post your skybox files so other people can verify the issue.
