### ISSUE TITLE
'Failed to load effect mapping for the following objects'

### ISSUE THREAD

**Issue by Neoly805** [ray-cast/ray-mmd#132]
Hi, can someone help me solve this problem? Usually it pops up when I want to load a pmm file into 'Kyouki Ranbu'. When I get this error, I can't load any effects. I really want to make a video with effects.
![Inkedproblem_LI](https://user-images.githubusercontent.com/70794714/141645911-3636630f-7c64-4962-bf8f-0e2c9fda02ef.jpg)

**Comment by sennxes** [comment]
I find this error usually occurs if you've either changed the location of the model and adjusted in the .emm file -successfully-,
or have made any adjustments to the models .pmx structure resulting in fewer material subsets (while increasing material subsets usually just offsets the materials by the number of new subsets added).
I believe if you've made adjustments to your model, its likely that it will no longer load the previously saved materials and you will have to re-map the materials to the subsets and re-save. This may not be 100% accurate to your specific situation, but this is the experience i have gone through far too many times when encountering this error.
