### ISSUE TITLE
#Ask

### ISSUE THREAD

**Issue by Chocolalolz** [ray-cast/ray-mmd#139]
On this software has model from "mahouka koukou no rettousei " 

I haven't use PC yet since I'm using phone while making this thread. Thx in advice

**Comment by AkagiVoid** [comment]
Hmm dis one?
https://www.deviantart.com/aceyoen/art/MMD-Shiba-Tatsuya-Download-701992846

Although dats one only one I see dat gots a DL link r8t off the bat.
(Use google for search mar MMD models. :3 )
