### ISSUE TITLE
ID3DXEffectCompiler: Compilation Failed

### ISSUE THREAD

**Issue by MarieRose1301** [ray-cast/ray-mmd#16]
I've updated to ray-mmd 1.2.0 today and as soon as i load the skylighting_hdr.fx on the skydome MMD either crashes or shows this error dialog. How do I fix it?
![1](https://cloud.githubusercontent.com/assets/20154978/21625318/c3196acc-d213-11e6-80cf-012818ad087d.PNG)

**Comment by ray-cast** [comment]
I have already known this question. but i can't fix it now.
But you can also try to use below ways to fix it.
![image](https://cloud.githubusercontent.com/assets/6936875/21627100/6d4dc61e-d250-11e6-868a-f14a8b474d8e.png)

**Comment by MarieRose1301** [comment]
Thank you so much, it works now

**Comment by MarieRose1301** [comment]
I'm sorry but I got another issue with skydomes, this time it's the Invalid Data error...
![3](https://cloud.githubusercontent.com/assets/20154978/21697715/59c5adf8-d39c-11e6-8fca-88712614cf08.PNG)

**Comment by ray-cast** [comment]
i had checked it out and i didnt find anything wrong, but could you please show me your directory with skybox and skybox/texture？i want to check it again.

**Comment by MarieRose1301** [comment]
Here:
![3](https://cloud.githubusercontent.com/assets/20154978/21712866/b2fc8744-d3ff-11e6-989d-d3f82b9b4ab7.PNG)
![4](https://cloud.githubusercontent.com/assets/20154978/21712867/b2ff657c-d3ff-11e6-8b6d-bbad30796a57.PNG)
I used the cmft which comes with the v2.2.0

**Comment by ray-cast** [comment]
![image](https://cloud.githubusercontent.com/assets/6936875/21717208/823b5c84-d44a-11e6-8597-c86f9fe0734b.png)
Maybe your HDRi (skybox.hdr) size/dimensions is too large, it must be less than 8k, so you can try to scale it down 3200x1600.

**Comment by MarieRose1301** [comment]
Oh thank you so much it does work now
I didn't know about this limit, my HDR size was 8000x4000

**Comment by MarieRose1301** [comment]
Although it's strange how these skydomes worked once before

**Comment by ray-cast** [comment]
I don't know either, but it may be a problem with MME or memory.
