### ISSUE TITLE
Alpha Channels

### ISSUE THREAD

**Issue by MarieRose1301** [ray-cast/ray-mmd#17]
It's not an issue per-se but I was wondering what's wrong with the alpha channels on layered parts with alpha, like hair. The effect itself is the best one I've ever used, though it's sad that the alpha channels don't work as expected. Will this be fixed in the future?
This is how the raw model looks:
![2](https://cloud.githubusercontent.com/assets/20154978/21652933/7edd79b2-d2b7-11e6-8c74-9a47618d5127.PNG)
And this is how it looks with the effect applied:
![1](https://cloud.githubusercontent.com/assets/20154978/21652946/8c08b106-d2b7-11e6-8941-145fc6cdc55f.PNG)
I'm using the hair material and main_ex.fx

**Comment by ray-cast** [comment]
yes, i know, but now i can't support it, because i'm using the deferrend shading, it does not support alpha transparency with multiple layer on the deferred render, btw, the raw-model in forward mode work, this mode is supportd.
