### ISSUE TITLE
README中效果图的素材能提供下载吗？

### ISSUE THREAD

**Issue by ysc3839** [ray-cast/ray-mmd#18]
如 https://github.com/ray-cast/images/raw/master/floor.png 图片中的地面

**Comment by ray-cast** [comment]
这个地板我现在也找不到了，那是之前我朋友在blender里随便帮我建的一个

**Comment by ysc3839** [comment]
好吧。还想问问这个地板是不是只是一个贴图？还是模型？

**Comment by ray-cast** [comment]
嗯，一个法线，一个光滑度，一个albedo的贴图

**Comment by ysc3839** [comment]
那还有其他的下载吗？

**Comment by ray-cast** [comment]
没，我测试场景很少的，就那么几个换来换去。。懒得找

**Comment by ysc3839** [comment]
好吧
