### ISSUE TITLE
Cannot use two normal maps anymore because NORMAL_MAP and NORMAL_MAP_SUB are interferring with each other

### ISSUE THREAD

**Issue by matadere** [ray-cast/ray-mmd#20]
Enabling `NORMAL_MAP_IN_SPHEREMAP` causes `NORMAL_MAP_SUB` to also look into the spheremap instead of using its own designated normal map file.
![ray120](https://cloud.githubusercontent.com/assets/1457491/21879494/d21d5a74-d8cb-11e6-8b2e-5e4f2e4a9614.jpg)
Adding `NORMAL_MAP_SUB_IN_SPHEREMAP 0` doesn't help either.
This was never an issue in the previous versions (example with v1.1.0):
![ray110](https://cloud.githubusercontent.com/assets/1457491/21879518/ecda8b20-d8cb-11e6-8183-6c391fe97c02.jpg)
Switching their role causes error:
![switcherror](https://cloud.githubusercontent.com/assets/1457491/21879608/79a9af40-d8cc-11e6-9fa2-16cd1e3ec1e6.jpg)
Well, I don't really care about the error as long as they can do their job as usual. 
Thank you for making an amazing shader!

**Comment by ray-cast** [comment]
oh, sorry for my delay reply, but i have already fixed the problem, you can download it again.

**Comment by matadere** [comment]
It works now. thanks!

**Comment by ray-cast** [comment]
my pleasure.
