### ISSUE TITLE
Normal Map animation for water?

### ISSUE THREAD

**Issue by MarieRose1301** [ray-cast/ray-mmd#21]
Hello, is it possible to use gif animated normal maps to simulate water effect?
Or maybe there's some other way to make water-like effect?

**Comment by ray-cast** [comment]
ok, i will add an animation to normal map

**Comment by ray-cast** [comment]
it's already added in dev version

**Comment by MarieRose1301** [comment]
that was fast, thank you so much for your awesome work :33
