### ISSUE TITLE
Unable to render

### ISSUE THREAD

**Issue by MarieRose1301** [ray-cast/ray-mmd#23]
Hello, I've encountered a problem while rendering a video while using my custom materials. How can i fix that? Or is my PC too weak? ![capture](https://cloud.githubusercontent.com/assets/20154978/24590459/295636da-17f6-11e7-83cd-c0f1f7499663.PNG)

**Comment by ray-cast** [comment]
sorry for delay replay, i don't know how it happened, can you show me text in your material.fx?
