### ISSUE TITLE
Hair bug

### ISSUE THREAD

**Issue by Janine-Alencar** [ray-cast/ray-mmd#24]
When I put the ray.x on MMD the hair became neon green (on 1.0.7), black (1.3.1) or white (alpha). I tested on other models and have the same problem.

**Comment by ray-cast** [comment]
check your Main, MaterialMap, EnvLighting tabs
in the MME dialog box, the main tab should be assigned a "main.fx"
in the MME dialog box, the materials tab should be assigned the "material_xxx.fx"
in the MME dialog box, the EnvLighting tab must be assigned a skylighting.fx from your skybox folder
For exmaple :
![image](https://cloud.githubusercontent.com/assets/6936875/26725270/4ae2b24c-47d0-11e7-95ae-b61cf8a18ffd.png)
![image](https://cloud.githubusercontent.com/assets/6936875/26725273/55966724-47d0-11e7-8945-38d3e95eadcd.png)

![image](https://cloud.githubusercontent.com/assets/6936875/26725254/3790b0f4-47d0-11e7-9ec8-d08cb123c0b1.png)

**Comment by Janine-Alencar** [comment]
ty :D
