### ISSUE TITLE
Multi light shadows

### ISSUE THREAD

**Issue by haolink** [ray-cast/ray-mmd#25]
Hello,

first of all: Absolutely amazing work on this effect, I really love it. It's fast and it looks very great.
I also like how you added the option to have multiple light sources - now this is where a tiny problem is coming in: only the sun seems to be causing ground shadows:

I've made a demo screensoht below.

![shadow_pointlights](https://user-images.githubusercontent.com/5476865/26983316-a7971b2a-4d3b-11e7-8b90-05b30d74d55c.jpg)

As you can see the model in the picture is causing a sun shadow to the left - the light source however should cause anought shadow to the back right. Am I doing something wrong or will this come in the future?

**Comment by Wampa842** [comment]
When you load both Ray-MMD and one of its multi-light sources, a new tab will appear in the MME called "LightMap". Click on it, find the light source, and click "Set Effect".
You'll notice that next to the effect that's applied to the light (e.g. IES_Lighting.fx), there are similarly named .fx files (IES_Lighting_s0.fx to _s3.fx), which are shadow-casting lights. The number marks the resolution of the shadow map.

**Comment by haolink** [comment]
Thank you so much, I didn't find that on my own.

It's working great!
