### ISSUE TITLE
Colored specular maps

### ISSUE THREAD

**Issue by MarieRose1301** [ray-cast/ray-mmd#27]
Hello, I've been trying to get the specular maps to work, but i haven't been able to get them reflect the color they should, they all reflect the environment color or not even reflect anything at all

**Comment by ray-cast** [comment]
the specular maps are not HDR/environment maps, it only modifies the color of basic reflection of the model, then apply the basic reflection to multiplies it by the color of the environment, but it's only a very small contribution to change the  color of environment reflect, when the material has a low smoothness or the albedo color brighter

**Comment by MarieRose1301** [comment]
Oh I get it now, thank you so much
