### ISSUE TITLE
Black screen when post-process sharpen is disabled

### ISSUE THREAD

**Issue by Wampa842** [ray-cast/ray-mmd#29]
Since post-process sharpen was added, loading the effect with sharpening disabled results in a black screen - only the model's bones are visible. When it is enabled, the effect functions as usual.
[Post-process sharpen is disabled...](https://user-images.githubusercontent.com/20817298/27998433-3f47b37c-650f-11e7-919b-aea3aa747c74.png)
[...and enabled.](https://user-images.githubusercontent.com/20817298/27998434-429d55f4-650f-11e7-9dd8-33bafccc6047.png)
The issue has existed since [commit d625d63992c477924835d068d61c6f8278fab482](https://github.com/ray-cast/ray-mmd/commit/d625d63992c477924835d068d61c6f8278fab482). I was able to work around the issue by defining POSTPROCESS_SHARPEN as 1 when it was removed from the config, but a recent commit removed parts of ray.fx that enabled sharpening entirely.

I'm running 64-bit MMD on Windows 7 with a Radeon HD5550 graphics card.

**Comment by ray-cast** [comment]
it seems to have fixed the bug, you can download current version of the dev again and help me to test it, is it still in current version for me?

**Comment by Wampa842** [comment]
I've just cloned the most recent branches - the issue exists in both Developing and Alpha.

**Comment by ray-cast** [comment]
ok, thanks, i will looking into fix it out and reply you later

**Comment by ray-cast** [comment]
seems to fixed, you can try to download dev version again or copy&paste this link to your ray.fx file, and please let me know if it still exists in the dev.
https://raw.githubusercontent.com/ray-cast/ray-mmd/developing/ray.fx

**Comment by ray-cast** [comment]
or close the issue

**Comment by Wampa842** [comment]
I've updated the file - the issue is fixed. Thank you.
