### ISSUE TITLE
DirectX error

### ISSUE THREAD

**Issue by MarieRose1301** [ray-cast/ray-mmd#30]
After a while, I've tried loading ray again and got that error, do you know what could it be? I never got that one before ![capture](https://user-images.githubusercontent.com/20154978/31289777-b443647e-aad2-11e7-8afa-5fb05a09e03e.PNG)

**Comment by ray-cast** [comment]
Can you show me that video memory usage before this error? It seems caused by small memory or unsupported shader model

**Comment by MarieRose1301** [comment]
After I start loading skylighting_fast ![image](https://user-images.githubusercontent.com/20154978/31320221-608f71bc-ac79-11e7-9932-bd6c6eb80dd3.png)
I have never had this issue on this PC before it's so strange

**Comment by MarieRose1301** [comment]
weird it actually loaded now :/ sorry

**Comment by ray-cast** [comment]
okay, btw, in the most cases, it seems caused by memory, and well, MMD has a caching mechanism that will be always occupy your memory and video memory, so you can restart MMD to release the memory, once you see this error again
