### ISSUE TITLE
Melanin?

### ISSUE THREAD

**Issue by MarieRose1301** [ray-cast/ray-mmd#32]
Is there a way to enable the use of melanin maps in newer versions of the effect? I've tried defining the MELANIN_MAP in material 2.0 but it didn't change anything

**Comment by ray-cast** [comment]
![image](https://user-images.githubusercontent.com/6936875/31928183-b3f0e94c-b8c9-11e7-8a4a-30a93eff807e.png)

It has moved into the ALBEDO_SUB_MAP_ENABLE, set 4 to ALBEDO_SUB_MAP_ENABLE and modify the albedoSub for Melanin

**Comment by MarieRose1301** [comment]
Thank you so much, didn't notice this >w<
