### ISSUE TITLE
Wetness.....

### ISSUE THREAD

**Issue by penti-jp** [ray-cast/ray-mmd#33]
Adding the Wetness setting to the file where the material setting has been completed will make it yellow and can not set Wetness.
Water can be set without problems.

![ray_barbed_wire_wetness](https://user-images.githubusercontent.com/32807994/31942521-7e8c2352-b900-11e7-9ed9-d299e090a1e7.png)

**Comment by ray-cast** [comment]
okay, thanks, i'll fix it later and sorry for delay replay

**Comment by penti-jp** [comment]
Okey, understood.aim not in a hurry.

**Comment by ray-cast** [comment]
it seems to be fixed now, thanks for your issue, just DL again and 
copy and overwrite the wetness/water from the programmable folder to your material directory

**Comment by penti-jp** [comment]
Thanks for taking the time. The problem was fixed. Thank U very much.
