### ISSUE TITLE
Part of the shadow of the spotlight is not rendered.

### ISSUE THREAD

**Issue by gaj-cg** [ray-cast/ray-mmd#34]
[Description]
There is a case that one frame of part of the shadow of the spotlight is not rendered during MMD playback.
The non-rendered portion is a small rectangle.

[Version]
1.3.1 , developing(commit e923b24)

[Steps to reproduce]
1.setup
  1)ray.x,skybox(Sky Hemisphere/Template),ray_controller.pmx  into the MMD and turn off the anti-aliasing.
  2)Add Materials/Programmable/Water/water.pmx to MMD, and select Main.fx in the main section. Use it as a wall.
  3)Add any model to MMD, and select Main.fx in the main section.
  4)Add SpotLight.pmx to MMD, and select spot_lighting_with_shadow_*.fx in the LightMap section.
2.Set 1000 to the end frame of the Play panel.
3.Click the Play button.
Similarly, you can confirm by setting the mode of physical operation to trace mode and pressing the right cursor key.
![spotlightshadow_bug_developing_s](https://user-images.githubusercontent.com/32675616/32064271-517af8ec-bab4-11e7-9776-76b3136508d3.png)

**Comment by ray-cast** [comment]
Thanks for your steps
but now i'm busying, please wait for a moment, i'll try to fix it by your steps

btw that water's material cannot be used in develop yet, i've recently modified the material_common_2.0.fxsub, the resulting material_common_2.0.fxsub cannot be used with water and wetness now

**Comment by gaj-cg** [comment]
I am not in a hurry so it's okay ;)

I understand that it is the developing branch. Thank you for the information.

**Comment by ray-cast** [comment]
Looks like it's fixed now, but if the problem still exists, please let me know

**Comment by gaj-cg** [comment]
I confirmed that the problem was fixed at 96b6da9.
Thank you very much.
