### ISSUE TITLE
Model remains black even after applying material + main.fx + skybox

### ISSUE THREAD

**Issue by PastMemories** [ray-cast/ray-mmd#37]
Strangely enough, a particular model seems to remain 'black' even with main.fx on and the materials applied in MaterialMap. This model is Bumblebee (https://bowlroll.net/file/149881 - the one in the middle in the picture) while the other two models I show here function normally under the usual circumstances. 

In the first picture, all three are using the ClearCoat material. It is to be noted that using other material types results in the same problem for the model in the middle, as seen in the 2nd picture where all three are using the Metallic ~ Flat ingot rough (material_rough_metal) material. 3rd picture shows the affected model's original colours without raycast.

I don't know the reason why the model in question is being this way, but I hope this is something that's fixable. 

![test](https://user-images.githubusercontent.com/33811485/32994011-0d44ff06-cd9c-11e7-8d1f-e2bb1716f81d.png)
![bleh](https://user-images.githubusercontent.com/33811485/32994037-9ac7b670-cd9c-11e7-8971-3e8bdb795af6.png)
![aaa](https://user-images.githubusercontent.com/33811485/32994056-ef040c20-cd9c-11e7-9a37-d7a1e2d47276.png)

**Comment by ray-cast** [comment]
Some models are rendered in MMD by using ambient color as (diffuse color / albedo), so you need to modify the ambient color to diffuse color, or change the ALBEDO_MAP_FROM to 7, that will fix your problem i think
![image](https://user-images.githubusercontent.com/6936875/33001556-9e137e52-cde9-11e7-957b-aade51230c5d.png)
![image](https://user-images.githubusercontent.com/6936875/33001564-a9239ae8-cde9-11e7-83f6-6fa1d91f3ec7.png)

**Comment by PastMemories** [comment]
How do you 'change the ALBEDO_MAP_FROM to 7'? I'd like to try that before resorting to editing the colours, if you don't mind telling.

**Comment by ray-cast** [comment]
Duplicate and open a material_2.0.fx file.then modify the ALBEDO_MAP_FROM like below image,
![image](https://user-images.githubusercontent.com/6936875/33002549-d90cd390-cdef-11e7-9ebf-4e60b790fcad.png)

And assign this material.fx to your subset 2 of (bumblebee_rid_2.0)
![image](https://user-images.githubusercontent.com/6936875/33002656-7c4ffc30-cdf0-11e7-8114-095634a140dc.png)

**Comment by PastMemories** [comment]
Hmm... that doesn't really work, sadly. It still retains the black colour.

When applied to subset2, all other materials having no fx:
![how sad](https://user-images.githubusercontent.com/33811485/33002910-253d315e-cdf2-11e7-9dcf-0170f6d541f7.jpg)

When all materials have the edited fx:
![poof](https://user-images.githubusercontent.com/33811485/33002921-3b5a0b9c-cdf2-11e7-920f-82882813ccf3.jpg)

However, the edit works. Changing all materials from ambient to diffuse colour fixed the problem, albeit leaving the model discoloured if raycast is not put into MMD.

Left: Original, Right: Edited

![ori and edited](https://user-images.githubusercontent.com/33811485/33002593-18f5e53c-cdf0-11e7-8628-7ce5deaa9420.jpg)
![nyeh](https://user-images.githubusercontent.com/33811485/33002640-62951258-cdf0-11e7-9955-902dac7b85f5.jpg)

**Comment by ray-cast** [comment]
It seems working now in:
set the ALBEDO_MAP_FROM to 7 
and 
set the ALBEDO_MAP_APPLY_DIFFUSE  to 0
![image](https://user-images.githubusercontent.com/6936875/33003679-26743c52-cdf7-11e7-9df6-0ef1670d68b9.png)

**Comment by ray-cast** [comment]
You need to download a new material_common.fxsub and put this file into your Materials directory and overwrite your old file material_common_2.0.fxsub

download link:
https://raw.githubusercontent.com/ray-cast/ray-mmd/developing/Materials/material_common_2.0.fxsub

**Comment by PastMemories** [comment]
I'm starting to get a bit confused, sorry... can I recap that so I can see if the directions are correct?

- material_2.0.fx still has ALBEDO_MAP_FROM to 7 and ALBEDO_MAP_APPLY_DIFFUSE to 0
- overwrite old material_common_2.0.fxsub with the new one
- download a new material_common.fxsub

Is that all? I'm using ray-mmd-140beta3, should I change to the developing version or stick to my current one?

**Comment by ray-cast** [comment]
oh, it only works with dev version, so if you want to go fast, just download develop version and start over with your project and :
* Copy and open the material_2.0fx
* Edit ALBEDO_MAP_FROM  to 7 and ALBEDO_MAP_APPLY_DIFFUSE to 0
* Assign it to subset of model in MaterialMap

**Comment by PastMemories** [comment]
It works now, though the model admittedly looks dull due to it being just basic materials. Hopefully one day you'll find out how to properly fix this, but thanks for the help!

![it works](https://user-images.githubusercontent.com/33811485/33006216-75cdb2e4-ce04-11e7-9be0-f44ff68a10d0.jpeg)

**Comment by ray-cast** [comment]
Hmm, sorry for if i misunderstand, i think you seems to have misunderstand my point?
>  just basic materials, Hopefully one day you'll find out how to properly fix this

If you want to use others material for the same things to work with ambient color
You can fix this problem by 
Edit materials with ALBEDO_MAP_FROM and ALBEDO_MAP_APPLY_DIFFUSE
Or 
Edit materials of PMX model from ambient to diffuse color

Because MMD is calculated by using ambient and diffuse color, but ray only needs a diffuse color.
