### ISSUE TITLE
Low self-shadow resolution

### ISSUE THREAD

**Issue by MarieRose1301** [ray-cast/ray-mmd#38]
Hello, I was setting up a scene when I noticed the self shadow looking rather strange. Is it issue with my hardware or am I doing something wrong and is there a way for me to get this thing fixed? ![image](https://user-images.githubusercontent.com/20154978/33124517-ea37d5c4-cf85-11e7-9719-46fcf32631ab.png)

**Comment by ray-cast** [comment]
In order to calculate the shadow of large scene, that caused shadow looks not smooth is due to float-precision, For higher precision of shadow, suggest you use a `SpotLight.pmx` instead.

**Comment by MarieRose1301** [comment]
@ray-cast Thank you so much, it's working well with spotlight
