### ISSUE TITLE
Sweat material?

### ISSUE THREAD

**Issue by MarieRose1301** [ray-cast/ray-mmd#39]
Hello again, it's not an issue but just a question: i'm trying to make a sweat-like material but it never ends up looking believable. Do you have any tips on making it look more like it? I've tried using wetness maps but they look more like they are meant to be used on concrete etc :/

**Comment by Syloid** [comment]
Well, in my case what I usually do is put the Smoothness to 0.6-0.8 and It will look like "sweetie", nothing else.

-RedEyed Jealousy

**Comment by MarieRose1301** [comment]
@Syloid It would work on anime models, not realistic ones. And i don't need it to look like reflective glass,more like sweat drips(which look horrible when used as smoothness maps)

**Comment by Syloid** [comment]
@MarieRose1301 Then I can't help :c

**Comment by ray-cast** [comment]
@MarieRose1301  Sorry, i also can't help, i have never done anything like sweat or water drop, but i think it's easier to get it from someone such as skyrim mods and witcher 3 forum

**Comment by MarieRose1301** [comment]
I've found some effect in case anyone needs it (it's ray compatible) but for some reason it looks very bad on my models(even tho it's UV dependent and my UVs are clean) https://ux.getuploader.com/ikeno/download/9
![image](https://user-images.githubusercontent.com/20154978/33235246-d3fb3fe4-d23c-11e7-80c1-27836d7257f3.png)
![image](https://user-images.githubusercontent.com/20154978/33235248-dc7b576c-d23c-11e7-9601-836cb6e745b6.png)
