### ISSUE TITLE
HELP me please! problem with a green flter when lightmap is applied

### ISSUE THREAD

**Issue by caiovinicioso** [ray-cast/ray-mmd#44]
![sem titulo](https://user-images.githubusercontent.com/34377335/33773276-79d0f89c-dc1e-11e7-83ab-31cf50eb4b3d.jpg)

I used ray cast for a while one day suddenly everything started to turn green
I already tried using all skybox but the problem does not go away
I already changed versions of ray cast and mmd but it did not work
I know the problem is with the lightmap everything works normally until I apply the light map
and everything turns green suddenly
and I've tried everything to solve it, but I could not the problem persists even when rendering
please help me

**Comment by ray-cast** [comment]
Please send me that images where each tab of the MME panel, i need to know what *.fx to use in each model
![image](https://user-images.githubusercontent.com/6936875/33775771-5f17914e-dc7a-11e7-9b94-8346f34a71fb.png)

**Comment by caiovinicioso** [comment]
![sem titulo](https://user-images.githubusercontent.com/34377335/33791572-e0370530-dc74-11e7-915a-abe57a8b8f33.jpg)

**Comment by ray-cast** [comment]
Cancel this `.fx`, and assign a `Sky with lighting.fx` to `skybox.pmx` in the `EnvLightMap`
![image](https://user-images.githubusercontent.com/6936875/33791723-6cbd3c6c-dccb-11e7-8149-cc131be7aa32.png)

**Comment by caiovinicioso** [comment]
![sem titulo](https://user-images.githubusercontent.com/34377335/33791836-cba85768-dc79-11e7-9b07-ed8f4ee06c5e.png)

the green is gone!! <3 ... but now everything is very white??...

**Comment by ray-cast** [comment]
Cancel this one again
![image](https://user-images.githubusercontent.com/6936875/33791941-5d3036d8-dccf-11e7-96d7-bcae5e9bbe6a.png)

**Comment by caiovinicioso** [comment]
![image](https://user-images.githubusercontent.com/34377335/33791953-e899f6d6-dc7b-11e7-805c-fe2505bd1e30.png)
It worked!!!
but....
after deactivating the lightmap the fog effect does not work T.T

**Comment by caiovinicioso** [comment]
![image](https://user-images.githubusercontent.com/34377335/33792159-b11da2da-dc7f-11e7-8493-4272dba788f9.png)

that definitely worked
thank you so much!
I'll do fog effect with ikgodray
thank you very very much I love ray-mmd <3

**Comment by ray-cast** [comment]
okay, thank you
