### ISSUE TITLE
关于光影

### ISSUE THREAD

**Issue by Adonis-Otogari** [ray-cast/ray-mmd#45]
![tim 20171210140000](https://user-images.githubusercontent.com/22231298/33802446-829b4c26-ddb2-11e7-9e17-5923ee28ccb7.png)
![tim 20171210135931](https://user-images.githubusercontent.com/22231298/33802447-83885d04-ddb2-11e7-918d-0e5077bb72c8.png)
场景是一个比较暗的然后有部分要发光，在controller调试到满意的效果后拉回camera就全黑了……是什么mme的设置问题吗？
还有一个问题就是人物放进去之后白色布料和皮肤都发光发得看上去很不自然……就像这样
![tim 20171210140350](https://user-images.githubusercontent.com/22231298/33802471-02fb77ba-ddb3-11e7-91b6-4611a34b1958.png)
所有设置都在这里。麻烦解答啦！
![_meitu_0](https://user-images.githubusercontent.com/22231298/33802505-95976a70-ddb3-11e7-9a24-67b221c15f02.jpg)
最后还有个小问题，ray大的群验证问题是什么意思呀……b站地址是指？试了下bilibili.tv被拒绝啦;w;

**Comment by ray-cast** [comment]
main板块的fx应该挂main.fx，
然后EnvLightMap挂skybox目录中任意目录中的sky_with_lighting.fx,
群的验证问题就是你b站的用户地址，如果没有作品的话就不让进了
