### ISSUE TITLE
error in fog effect !

### ISSUE THREAD

**Issue by caiovinicioso** [ray-cast/ray-mmd#46]
![sem titulo](https://user-images.githubusercontent.com/34377335/33810793-5bfad68e-ddf0-11e7-8670-471769ba3ed6.jpg)
Sorry to bother you again but I have the following problem
I can use lighting very high medium and low.
but fog very high or medium or low does not work
the image error appears
there is a way to solve it ?

**Comment by ray-cast** [comment]
sorry, it's work well on my pc, i'm not clear yet why cannot work with some other pc

**Comment by ray-cast** [comment]
seems fixed now, please download dev branch again

**Comment by caiovinicioso** [comment]
the problem get solved thank you very much! <3
