### ISSUE TITLE
Specular map color with anisotropy(or custom)

### ISSUE THREAD

**Issue by MarieRose1301** [ray-cast/ray-mmd#48]
I'm trying to do something like this but i can only have either specular color or anisotropy, is it possible to make everything work together? ![image](https://user-images.githubusercontent.com/20154978/34105950-00e48e24-e3ff-11e7-81a1-b0ff4ab8e31c.png)

**Comment by ray-cast** [comment]
When enabled custom, that specular map will not work with RGB color is due to being gbuffer-space, 
But you can put a Grayscale specular map by sets the SPECULAR_MAP_TYPE to 2

**Comment by ray-cast** [comment]
sorry, it's impossible for me to make it now

**Comment by MarieRose1301** [comment]
oh okay, thanks for the reply :3
