### ISSUE TITLE
sphere maps and normal maps

### ISSUE THREAD

**Issue by MarieRose1301** [ray-cast/ray-mmd#49]
I'm so sorry for spamming you with questions but is it possible to make material normal maps to affect the sphere maps when using main fx with sphere map?

**Comment by ray-cast** [comment]
yes, wait for a while, i'll add some entries of normal map into the main.fx

**Comment by ray-cast** [comment]
It worked now, please copy and paste the main folder from github page to your main folder
![image](https://user-images.githubusercontent.com/6936875/34208068-e383c5b4-e5c7-11e7-87d1-dd34ee30a7f9.png)

![image](https://user-images.githubusercontent.com/6936875/34208056-d8b4af0e-e5c7-11e7-90ed-beb0719f3871.png)

**Comment by ray-cast** [comment]
Duplicate and open a main fx and enter a path to your normal  and matcap map

**Comment by MarieRose1301** [comment]
thank you so much, it works great
