### ISSUE TITLE
About Dispersion Radius slider setting

### ISSUE THREAD

**Issue by penti-mmd** [ray-cast/ray-mmd#50]
Rebase for Vignette, Thank you. I have a question. Dispersion Radius slider setting seems to be maximized at 0, minimal at 1, but is it okay now?

**Comment by ray-cast** [comment]
hmm, that a Dispersion function has a minimum value at 0, and maximum at 1, used to controls how much radius that does not produces this effect in the screen center,  no effect at 0, fully effect at 1

**Comment by penti-mmd** [comment]
Yeah, I think so. Actually it looks like this. Dispersion is set to 0.5.
The first one is Dispersion Radius setting 0.0, the second piece is 1.0.
![ray_karume_all_issue01](https://user-images.githubusercontent.com/32807994/34316697-57009c2e-e7df-11e7-9352-e77c5aba31c4.png)
![ray_karume_all_issue02](https://user-images.githubusercontent.com/32807994/34316698-5a671a64-e7df-11e7-9104-316424940b54.png)

**Comment by ray-cast** [comment]
sorry, i might not understand your question yet, could you tell me more in details about your question? i don't think it has a problem or a bug?

**Comment by penti-mmd** [comment]
Sorry to be confusing. "Dispersion Radius" recognizes it as Effect that gives curvature to the screen. However, now it's 0.0 with the effect full, 1.0 it seems no effect.
It was a question of whether it is a problem as a set value.

**Comment by ray-cast** [comment]
Color shift has two parameters, `Dispersion` and  `Dispersion Radius`.
`Dispersion Radius` is one of parameters, only controls the `Dispersion` parameter does not produces the color shifts on the whole screen.
so it will not work, when `Dispersion Radius` at zero, and i'm sure it works well

**Comment by penti-mmd** [comment]
OK, I understood.I am sorry for letting you take time.Thank you.
This issue close.
