### ISSUE TITLE
Mono channel speculars

### ISSUE THREAD

**Issue by MarieRose1301** [ray-cast/ray-mmd#51]
I'm having an issue with custom materials and specular maps
I intended to use a specular map with SSS material, however after leaving only 1 black and white channel on the texture I get an error saying that the map is RGB. how should the texture be saved in order for ray to read it as a mono channel texture? I've tried saving a black and white 8-bit jpg and png but none worked

**Comment by ray-cast** [comment]
just sets the `SPECULAR_MAP_TYPE` to 2 and enter the path to your specular map
