### ISSUE TITLE
Pixelated Glow

### ISSUE THREAD

**Issue by Syloid** [ray-cast/ray-mmd#52]
Hello, I don't really know if this is a ray-cast issue but sometimes when I put Emissive Material its Reflection looks pixelaed  like this.

![kddtbrp](https://user-images.githubusercontent.com/33935297/34396200-23763724-eb68-11e7-977e-deb43095f5eb.png)

**Comment by ray-cast** [comment]
Sorry, i can't fix it yet, i think it's caused by increase resolution or something else, so that samples are not enough to make it looks more smooth

**Comment by Syloid** [comment]
It could be because my resolution is 2560x1440 and it stretches it. Anyways, thank you for answering!

**Comment by ReonaWest** [comment]
ah hello as someone who has used emissive constantly in the past i can almost reassure you its due to the bloom.

**Comment by Syloid** [comment]
@ReonaWest Hey, i tried what you said by leaving the BloomThreshold to 0 but unfortunately it still shows up a bit as you can see here (if you zoom):
![test1080p](https://user-images.githubusercontent.com/33935297/35484814-ddbfbc44-0455-11e8-901a-1ea9b4964d35.

I tried to fix this myself by hardcoding more samples with my poor knowledge of programming but I failed :/

**Comment by Syloid** [comment]
@ReonaWest Hey, i tried what you said by leaving the BloomThreshold to 0 but unfortunately it still shows up a bit as you can see here (if you zoom):
![test1080p](https://user-images.githubusercontent.com/33935297/35484848-8feef20e-0456-11e8-9503-ba3f26f69484.jpg)


I tried to fix this myself by hardcoding more samples with my poor knowledge of programming but I failed :/

**Comment by ray-cast** [comment]
this was actually the problem i always wanted to solve, but this is not an easy problem, that it'll take me a long time to rewrite the all of the code, so i never got around to actually do,  but it will be solved in the future

**Comment by Amani747** [comment]
I have remedied this problem by changing:

in:
PostProcessBloom.fxsub

from:
static const float2 BloomScale = 512 * float2(ViewportAspect, 1);

to:
static const float2 BloomScale = 1024 * float2(ViewportAspect, 1);

**Comment by Syloid** [comment]
@Amani747 Thank you very much for sharing the solution in here

**Comment by Amani747** [comment]
No problem! Now keep in mind - I did not completely follow the code - I am not sure if this value is used to generate the frame buffer? dimensions needed to blur and generate the bloom effect. This may have solved the issue by simply offsetting some precision error, not REALLY solving the issue, or it may be scaling that buffer space which would completely solve the issue.

At this point - I know it solved the issue for me and a couple of others with no other side effects - so I would like to assume it is a good fix - Just be weary, this may be breaking something else.

Did it completely fix the issue for you as well?

**Comment by Syloid** [comment]
@Amani747 I don't know either, I would have to test it several times in order to see If that hotfix really has made it work but for the moment It seems it had because I haven't noticed any more pixelated glow thingys since I doubled the BloomScale constant like you said previously. \:D/

**Comment by Syloid** [comment]
Okay so, I've found the exact same project where this issue seemed to appear, and as you can see in those pictures, it looks like the fix @Amani747 told (https://github.com/ray-cast/ray-mmd/issues/52#issuecomment-397786062) really does the trick:

![fixed](https://user-images.githubusercontent.com/33935297/42419581-480cd02e-82b8-11e8-9117-d67e908fada4.png)
![pic2](https://user-images.githubusercontent.com/33935297/42419635-5b65f924-82b9-11e8-9171-3236af80aba5.png)


With that being said, I will have to Close the issue.
