### ISSUE TITLE
About"Better Skin when occlusion map is used"

### ISSUE THREAD

**Issue by dy2774** [ray-cast/ray-mmd#54]
这一项，我有点没明白，事实上mmd的角色模型似乎并没有看到有高模。
这一条该如何利用，自己画贴图吗？后面的预览ao截图是404。
PS:不会渲染算法。。只是学校上过一点图形学基础，有什么理解错误的地方抱歉。

**Comment by dy2774** [comment]
emmm,还是说，其实就是对低模烘培一张occ贴图就可以了？不是用高模烘培贴给低膜用？

**Comment by ray-cast** [comment]
链接在这里 [preview](https://raw.githubusercontent.com/ray-cast/ray-mmd/master/Shader/screenshots/ao.jpg)
大部分MMD的人物模型都是uv全展开的，高模烘培只不过是为了保留细节，所以低模一样是可以用来烘的，你可以用我之前写的Substance Painter的插件来烘培模型
 https://github.com/ray-cast/mmd-export

**Comment by duyang2774** [comment]
谢谢解答!
