### ISSUE TITLE
Glossy Skin & Smooth Shadows.

### ISSUE THREAD

**Issue by mmdlifeyt** [ray-cast/ray-mmd#55]
Is there is a still way for smooth shadow like this and
![2](https://user-images.githubusercontent.com/29914284/35470694-2bc54aa0-035f-11e8-97f2-a3cbeb0c7045.png)
and is there is a way for glossy skin like this.
![3](https://user-images.githubusercontent.com/29914284/35470722-c0e57cd6-035f-11e8-8d24-1cf487f45b5a.png)
It's not really a issue but i wanna know that sorry for bad english.

**Comment by ReonaWest** [comment]
Ah hello, a friend brought this to my attention. first off i want to start off with thanks for watching my videos!
well for the under cloud video, i made a hdr file that no one has and it gets me lighting like that along side my configurations in the .conf file and what i use in the controller.

As for the Electric curator, i used the human skin material and edited a bit to add "smoothness"(which in your terms is glossy) and the surrounding point lights attached to the models help enhance or even show the glossiness on the model and the floor(the umbrellas).

I'll be happy to answer anymore questions you have~

**Comment by ray-cast** [comment]
sorry, i can't give some tips with this issue, and thanks @ReonaWest for helping to answer this question.
