### ISSUE TITLE
Glitches on model

### ISSUE THREAD

**Issue by MiranaM** [ray-cast/ray-mmd#56]
Hello
I applied raycast on model and here are some glitches with face and neck. Is it model's issue or effect's? Are there any way to fix it?
![2](https://user-images.githubusercontent.com/18576616/35477318-5c0a4b80-03d1-11e8-8329-884c1979995d.png)

**Comment by ReonaWest** [comment]
do you mind sending me the model so i can see for myself what the problem is?

**Comment by ray-cast** [comment]
Hi,
This framework can only supports two layers of transparent material, it'll discard the some pixel when more than two transparent pixels in the same ray of view, so put your model in the PMXEditor and edit the hair material to remove the transparent, or delete the alpha channel from hair bitmap

**Comment by MiranaM** [comment]
@ReonaWest https://bowlroll.net/file/51741 it's not my model ^^" I picked the "カミュ(アニメカラー・マスク無し・マント無し)_ver2"
@ray-cast thank you, but i think the problem is not in hair because:
![default](https://user-images.githubusercontent.com/18576616/35483451-2f308142-0453-11e8-899e-2f3c303c724a.png)

**Comment by ray-cast** [comment]
It's works fine in my pc, i can't see any problem with this model,  please just tell me what i should be doing something?

**Comment by ray-cast** [comment]
okay , have fun
