### ISSUE TITLE
Real reflections?

### ISSUE THREAD

**Issue by MarieRose1301** [ray-cast/ray-mmd#57]
On your twitter I've seen how ray reflects a rectangular light source so i was wondering is it possible to make things like mirror or reflective floor with the effect?

**Comment by ray-cast** [comment]
no, the lighting and env reflection are two different types of algorithms, and in real-time the env reflection is almost a difficult thing for the all engines, this library can only works with DX9 env, that cannot supports the compute shader to create some env and conditions

**Comment by MarieRose1301** [comment]
ah, okay, thanks for the explanation hehe
