### ISSUE TITLE
求解

### ISSUE THREAD

**Issue by Vectorlika** [ray-cast/ray-mmd#6]
为什么我做出的LED屏幕想将图片放上去出现确是黑色的啊

**Comment by ray-cast** [comment]
图片的话，需要把路径写到材质里，然后rectangle_light.fx里再写一次路径，应该就可以了啊

**Comment by Vectorlika** [comment]
C:/Users/WZJ/Desktop/111.jpg 发光贴图和视频贴图都改成这样的路径了 就是黑色的，，，

**Comment by Vectorlika** [comment]
C:/Users/WZJ/Desktop/111.jpg 发光贴图和视频贴图都改成这样的路径了 就是黑色的，，，

**Comment by ray-cast** [comment]
你有改表情里的RGB么

**Comment by Vectorlika** [comment]
尝试改了之后没有变化啊

**Comment by ray-cast** [comment]
现在要睡觉了，你先加我Q吧 (资料里有)，RectangleLight一定要高度大于地面，范围最大，以及调节RGB，有了光照效果后，再加图片进去应该会有效果的，我刚试过一遍
