### ISSUE TITLE
SkyBox Time Of day can't load

### ISSUE THREAD

**Issue by ukimulki** [ray-cast/ray-mmd#60]
Hello forgive me for disturbing you, but i have question..i can't load sky Box/time of day. though I tried all the versions...Hope you can help me with this problem..:( 
![shader](https://user-images.githubusercontent.com/36558393/36338295-941e8f60-13dd-11e8-9b68-0620bc3a1b77.png)

**Comment by ray-cast** [comment]
It's fixed now, thanks for spotting this error, please click here: https://github.com/ray-cast/ray-mmd/archive/master.zip

**Comment by ukimulki** [comment]
Thanks for reply my problem..:D
when i download new ray cast and put in my MMD it getting dark like this..I really dont know happen..:(
![sky](https://user-images.githubusercontent.com/36558393/36360629-645b23c0-1558-11e8-823c-6458e70b9dc3.png)

**Comment by ray-cast** [comment]
please try to update your video driver or try another version of the mikumikueffect 037 x64bit ?

**Comment by ukimulki** [comment]
Thx..XD, i will try to update video driver, but for miku miku effect i use ver 037x32bit...whether to use 64xbit ver?

**Comment by ray-cast** [comment]
64 bit version of mikumikudance 926 above and mikumikueffect 037
