### ISSUE TITLE
The bone name of the light object is not displayed

### ISSUE THREAD

**Issue by gaj-cg** [ray-cast/ray-mmd#61]
[Description]
The bone name of the light object (e.g. DirectionalLight.pmx) is not displayed in Japanese Windows environment.
That was not only from version 1.5.1, but also from before.
![2018-03-12_22h00_59](https://user-images.githubusercontent.com/32675616/37291152-620ce1bc-2651-11e8-8f60-db437e9b6096.png)

[Version]
1.5.1（and below）

[workaround]
Change the name.
光源位置（顶）→光源位置（頂）
However, similar problems may occur in the Chinese Windows environment.
![2018-03-12_22h34_40](https://user-images.githubusercontent.com/32675616/37291220-9034a3fe-2651-11e8-8448-813498aa8916.png)
![2018-03-12_22h36_16](https://user-images.githubusercontent.com/32675616/37291244-98a15f0a-2651-11e8-8389-d5b4b5c9e654.png)

**Comment by ray-cast** [comment]
i see, thanks for spotting this problem.

**Comment by ray-cast** [comment]
i see, thanks for spotting this problem.

**Comment by gaj-cg** [comment]
I confirmed the fix. thx :)
![2018-03-13_21h13_31](https://user-images.githubusercontent.com/32675616/37341044-7563de0c-2703-11e8-9acc-7d5bf5bdc454.png)
