### ISSUE TITLE
Ray.x file doesn't work!

### ISSUE THREAD

**Issue by Fairydee** [ray-cast/ray-mmd#64]
Hello, i have a problem.
I had raycast on my computer before, but unfortunately I needed to delete all the files on it.
So when I tried to reinstall, the shader simply did not work, the file  "ray. x " was not doing anything!
That's when I tried to download other versions of MME and MMD, but nothing.
And no, It doesn't take long to load, just does nothing!

thank you!

**Comment by ray-cast** [comment]
please try to download 64bit version of MMD and MME, the ray.x cannot work well with 32bit version.
[MikuMikuDance](http://www.geocities.jp/higuchuu4/index_e.htm)
[MikuMikuEffect](https://bowlroll.net/file/35012)
