### ISSUE TITLE
SSSS+ not working?

### ISSUE THREAD

**Issue by kerubiel** [ray-cast/ray-mmd#65]
Hey, quick question.
When using the new updated ray, I can't get SSSS+ to work at all. 
I set the same materials and used the same skybox and everything.

![ssss-old](https://user-images.githubusercontent.com/37513243/37568909-fa98f6d2-2ab1-11e8-81b8-72289bd85c46.jpg)

I like how much smoother it looks with the SSSS+ in the older version (1.3.1).

![ssss-new](https://user-images.githubusercontent.com/37513243/37568912-08e13330-2ab2-11e8-843c-df033ec6116e.jpg)

But the new one (1.5) doesn't do that.

Am I just doing something wrong somehow?

**Comment by ray-cast** [comment]
it's caused by default AA(anti-aliasing),  please try to disable the AA

**Comment by kerubiel** [comment]
That did it. Thank you!
