### ISSUE TITLE
WOW

### ISSUE THREAD

**Issue by Kingwl** [ray-cast/ray-mmd#7]

**Comment by Kingwl** [comment]
it's very helpful to me

**Comment by Kingwl** [comment]
it's so cooooooooooooooooooool!!!

**Comment by Kingwl** [comment]
i love you baby

**Comment by AngryPowman** [comment]
Awesome

**Comment by GongT** [comment]
Greate work!

**Comment by ray-cast** [comment]
interesting

**Comment by hozuki** [comment]
![image](https://cloud.githubusercontent.com/assets/7345875/18808589/67ff2e76-8266-11e6-90e6-a9fb6c3069ff.png)
