### ISSUE TITLE
Grey skybox

### ISSUE THREAD

**Issue by Ranmit11** [ray-cast/ray-mmd#71]
When i try to load skybox time of the day it come up grey. Anyone can help me ? 
![grey skybox](https://user-images.githubusercontent.com/39659772/40581171-6210c44a-6106-11e8-96d6-f714d1d35ad0.PNG)

**Comment by ReonaWest** [comment]
Hello, you dont have MME installed which allows the fx applied to the skybox to display time of day.

**Comment by Ranmit11** [comment]
![capture](https://user-images.githubusercontent.com/39659772/42095989-11b65212-7b69-11e8-98c1-1cb8d0d7e685.PNG)
I have already installed all requirement. I just copying mme files to the mmd directory like everyone else, but nothing happened.

**Comment by gaj-cg** [comment]
It is a 32bit version.
Please install 64bit version.
http://ch.nicovideo.jp/beta183/blomaga/ar491222

**Comment by Ranmit11** [comment]
Thank you very much ! mme now is working
