### ISSUE TITLE
Weird Problem With Raycast

### ISSUE THREAD

**Issue by sleepymanakete** [ray-cast/ray-mmd#76]
It used to work fine for me but now at certain frames, it'll look weird like this:
![image](https://user-images.githubusercontent.com/30272172/41785110-cdc0750c-75fe-11e8-9e12-b345b5cfeddf.png)
then it goes back to normal:
![image](https://user-images.githubusercontent.com/30272172/41785284-5a90db48-75ff-11e8-9ff3-faf6525bebd0.png)

**Comment by ReonaWest** [comment]
Hello i can see you're using the BnS Rainbow motion. Raycast doesnt work with perspective turned off
![image](https://user-images.githubusercontent.com/35877691/41811379-5184615e-76c3-11e8-9b0f-47dfb0eac3c5.png)
Ive encountered this problem myself last year and this motion's camera has a lot of frames with perspective turned off. so make sure the perspective button stays on with all frames
![image](https://user-images.githubusercontent.com/35877691/41811392-83eb78ee-76c3-11e8-92e4-7c3539e396c7.png)

**Comment by sleepymanakete** [comment]
Hi, thanks so much!
