### ISSUE TITLE
Bundled textures

### ISSUE THREAD

**Issue by aokcubcg** [ray-cast/ray-mmd#8]
I was noticed that your product bundles my textures (++skies; 030).
/skybox/incskies030/texture/skybox.hdr
/skybox/incskies030/texture/skydiff_hdr.dds
/skybox/incskies030/texture/skyspec_hdr.dds

I really would like to thank you for your interest in my textures, however, basically I don't allow anyone to bundle ++skies; textures into their products, in either case the texture is "as-is", or with modification (includes resize, crop, color correction, etc). This is written in ++skies; user's guide, also hosted on github (https://github.com/aokcubcg/inkskies_terms/blob/master/terms.md) but in Japanese.

On the other hand, ++skies; textures can be bundled in your product with my permission.
If you hope so please contact me. I will check your product and say ok if there is no problem.

**Comment by ray-cast** [comment]
Sorry for breaking your rules , i'll delete it at once.

**Comment by ray-cast** [comment]
[![link text](https://github.com/ray-cast/images/raw/master/delete.png)](https://github.com/ray-cast/images/raw/master/delete.png)
I'm done, so sorry.

**Comment by aokcubcg** [comment]
Sorry for late response. Thanks for your quick action.

As I wrote, if you hope, I can allow you to bundle textures again (I can receive e-mail by aokcub3055 at gmail.com). Basically MMD users utilize my textures with png format but your shader enables using hdri in MMD. I feel it's exciting.

Anyway, this Issue now can be closed.

**Comment by ray-cast** [comment]
Thanks, but no thanks, 
I want to keep it below 35mb, bacause the project file size is too big, but you can see my README.md.
![image](https://cloud.githubusercontent.com/assets/6936875/19651626/35c4e04e-9a40-11e6-980b-316da12e075e.png)

**Comment by aokcubcg** [comment]
Understood, thanks for putting a link to me!
